language: go
sudo: required

go:
- 1.10.1

stages:
  - name: build
  - name: deploy
    if: type != pull_request

jobs:
  include:
    - stage: build
      env:
        global:
        - OPERATOR_VERSION="JOB_${TRAVIS_JOB_NUMBER}"
      name: "Build"
      install:
      - "./.travis/install.sh"
      script:
      - "./.travis/script.sh"
      after_success:
      - "./.travis/after_success.sh"

    - stage: deploy
      name: "Publish latest image"
      env:
        global:
        - OPERATOR_VERSION="${TRAVIS_BRANCH}"
      script:
      - "./.travis/publish-images.sh"

    - stage: deploy
      name: "Release"
      env:
        global:
        - OPERATOR_VERSION="${TRAVIS_BRANCH}"
      script:
      - "./.travis/release.sh"
      if: tag =~ /^release\/v.[\d\.]+(\-.*)?$/
