# This CR deploys Jaeger and Elasticsearch
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      resources:
    esIndexCleaner:
      enabled: true
      schedule: "*/30 * * * *"
      numberOfDays: 1
