# setup an elasticsearch with `make es`
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: two-replicas
spec:
  strategy: allInOne
  allInOne:
    size: 2
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
