name: "CI Workflow"
on: [push, pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jpkrohling/setup-operator-sdk@v1-release
      with:
        operator-sdk-version: v0.11.0

    - name: "basic checks"
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: ./.ci/script.sh
