name: "Continuous Integration Workflow"
on: [push, pull_request]

jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "make install"
      run: make install

    - name: "make ci"
      run: make ci

  e2e_elasticsearch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "make vendor setup-minikube"
      run: make vendor setup-minikube

    - name: "make es"
      run: make es

    - name: "make e2e-tests-es"
      run: make e2e-tests-es
